name: Test Chef Cookbook

on:
  pull_request:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1 
        with:
          ruby-version: '2.7'

      - name: Install ChefDK
        run: |
          curl -L https://omnitruck.chef.io/install.sh | sudo bash -s -- -P chefdk
          chef --version

      - name: Accept Chef license
        run: chef env --chef-license accept

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git
          sudo apt-get install -y build-essential
          chef exec bundle install --without development

      - name: Run Foodcritic
        run: |
          chef exec foodcritic ./resources

      - name: Run Cookstyle
        run: |
          chef exec cookstyle ./resources

      - name: Run Chefspec
        run: |
          chef exec rspec ./resources

      - name: Run Test Kitchen
        run: |
          sudo apt-get install -y libvirt-dev libvirt-daemon-system libvirt-clients
          chef exec kitchen test ./resources
